export const openings = [
  {
    id: 1,
    title: 'Senior React developer',
    experience: '(2+ yrs Exp.)',
    site: 'Remote',
    type: 'FullTime',
    desc: 'Join our dynamic tech team, leading the development of innovative software solutions. Bring your expertise to the forefront of digital transformation.',
    button: 'View details',
  },
  {
    id: 2,
    title: 'Senior React developer',
    experience: '(2+ yrs Exp.)',
    site: 'Remote',
    type: 'FullTime',
    desc: 'Join our dynamic tech team, leading the development of innovative software solutions. Bring your expertise to the forefront of digital transformation.',
    button: 'View details',
  },
  {
    id: 3,
    title: 'Senior React developer',
    experience: '(2+ yrs Exp.)',
    site: 'Remote',
    type: 'FullTime',
    desc: 'Join our dynamic tech team, leading the development of innovative software solutions. Bring your expertise to the forefront of digital transformation.',
    button: 'View details',
  },
  {
    id: 4,
    title: 'Senior React developer',
    experience: '(2+ yrs Exp.)',
    site: 'Remote',
    type: 'FullTime',
    desc: 'Join our dynamic tech team, leading the development of innovative software solutions. Bring your expertise to the forefront of digital transformation.',
    button: 'View details',
  },
  {
    id: 5,
    title: 'Senior React developer',
    experience: '(2+ yrs Exp.)',
    site: 'Remote',
    type: 'FullTime',
    desc: 'Join our dynamic tech team, leading the development of innovative software solutions. Bring your expertise to the forefront of digital transformation.',
    button: 'View details',
  },
];
