export { default as EmailLogo } from './icons/EmailLogo';
export { default as LocationMarkLogo } from './icons/LocationMarkLogo';
export { default as TelePhoneLogo } from './icons/TelePhoneLogo';
export { default as FacebookLogo } from './icons/FacebookLogo';
export { default as InstagramLogo } from './icons/InstagramLogo';
export { default as LinkedInLogo } from './icons/LinkedInLogo';
export { default as TwitterLogo } from './icons/TwitterLogo';
export { default as MinusIcon } from './icons/MinusIcon';
export { default as PlusIcon } from './icons/PlusIcon';
export { default as Arrow } from './icons/Arrow';
export { default as LeftArrow } from './icons/LeftArrow';
export { default as RightArrow } from './icons/RightArrow';
export { default as ProjectConsulting } from './icons/ProjectConsulting';
export { default as System } from './icons/System';
export { default as WebApp } from './icons/WebApp';
export { default as MobileApp } from './icons/MobileApp';
export { default as FeDev } from './icons/FeDev';
export { default as BeDev } from './icons/BeDev';
export { default as QaTest } from './icons/QaTest';
export { default as Support } from './icons/Support';
export { default as CustomDev } from './icons/CustomDev';
export { default as WebDesign } from './icons/WebDesign';
export { default as UiLib } from './icons/UiLib';
export { default as UiUxDev } from './icons/UiUxDev';
export { default as Hire } from './icons/Hire';
export { default as BgWave } from './BgWave';
export { default as StarIcon } from './icons/StarIcon';
export { default as HighlightArrow } from './icons/HighlightArrow';
export { default as StarsSVG } from './StarsSVG';
export { default as RectangleSVG } from './RectangleSVG';
export { default as BackgroundCircle } from './icons/BackgroundCircle';
export { default as ClosingQuote } from './icons/ClosingQuote';
export { default as BackgroundBubble } from './icons/BackgroundBubble';
export { default as BackgroundTriangle } from './icons/BackgroundTriangle';
export { default as BackgroundDonut } from './icons/BackgroundDonut';
export { default as Calender } from './icons/Calender';
export { default as DownArrow } from './icons/DownArrow';
export { default as LocationPin } from './icons/LocationPin';
export { default as Phone } from './icons/Phone';
export { default as Email } from './icons/Email';
export { default as Close } from './icons/Close';
export { default as BreadcrumbSeparator } from './icons/BreadcrumbSeparator';
export { default as BackgroundArc } from './icons/BackgroundArc';
export { default as BackgroundDonutShadow } from './icons/BackgroundDonutShadow';
export { default as BackgroundSemiCircle } from './icons/BackgroundSemiCircle';
export { default as Menu } from './icons/Menu';

export * from './heroSection';
export * from './ourClient';
export * from './navigation';
export * from './technologies';
export * from './blog';
